### ISSUE TITLE
Release the Kraken...

### ISSUE THREAD

**Issue by pbit** [burning-duck/rehace-github-magnolia#3]
The core of this project should be released as a separate npm module. 
It is not related to Magnolia or any other CMS out there.

**Comment by pbit** [comment]
https://wiki.magnolia-cms.com/display/WIKI/How+To+Open+Source+a+Light+Module

**Comment by pbit** [comment]
- [x] magnolia-light-module	Keywords in package.json
- [x] Description	In the README
- [x] Description	In package.json
- [x] README Features
- [x] README Usage
- [x] README Demo
- [x] README Screenshots
- [x] Small ? Your module provides one component, or a focussed set of functionality.
- [x] Directory Name	<what it is>-magnolia
- [x] Demo
- [x] Ready to use	npm package will be ready to be added to Magnoila resources directory.
- [x] License file
- [x] Github
- [x] module.yaml
- [x] .npmignore
- [x] buildable

**Comment by janroesler** [comment]
I added some screenshots (gif's), i think this shows the features from this light module.
But we need more details for the technical part (libraries, etc.)

**Comment by janroesler** [comment]
Add export (website.rehace-projects.xml) of the pages for demo in the _dev/demos folder.

**Comment by pbit** [comment]
v0.1.0 released: https://www.npmjs.com/package/rehace-github-magnolia
