### ISSUE TITLE
Use rehace module

### ISSUE THREAD

**Issue by pbit** [burning-duck/rehace-github-magnolia#9]
ReHaCe is now on npm.
https://www.npmjs.com/package/rehace

Remove internal implementation and use the package.

**Comment by janroesler** [comment]
Tested the branch https://github.com/burning-duck/rehace-github-magnolia/tree/use-rehace-from-npm 
Works on my machine :)

**Comment by pbit** [comment]
Think this is done...
V0.2.0 is on npm
